### ISSUE TITLE
Make plane fly across the screen.

### ISSUE THREAD

**Issue by richardlara67** [richardlara67/Balloon-Popper#3]
A plane needs to fly horizontally across somewhere around the top of the screen. 

Initial functions have been initialized, but need to execute. Reference **balloon-popper/docs/js/script.js** for more details.

**Comment by jordanhowe25** [comment]
I can work on this.

**Comment by richardlara67** [comment]
Go for it!

**Comment by richardlara67** [comment]
Completed by jordanhowe25
