### ISSUE TITLE
Different color balloons account for different score

### ISSUE THREAD

**Issue by richardlara67** [richardlara67/Balloon-Popper#4]
There are several colored balloons. Give each balloon color a different number of points towards the final score when popped.

**Comment by Gonzalo413** [comment]
I would like to work on this

**Comment by richardlara67** [comment]
Go for it!

**Comment by jordanhowe25** [comment]
I have submitted a pull request that includes this functionality.

**Comment by richardlara67** [comment]
Completed by Jordan.
