### ISSUE TITLE
Balloons fly up at different speeds

### ISSUE THREAD

**Issue by richardlara67** [richardlara67/Balloon-Popper#5]
**The speed at which the balloons fly up to the top of the screen will be time-sensitive. The longer the player stays at the game, the faster the balloons will be flying up to the top of the screen.**

Create a function for balloons to fly up to the top of the screen at different speeds. Use any means necessary to achieve the requirement stated above.

**Comment by jordanhowe25** [comment]
I added this enhancement in my last commit.  It increments based on the number of balloons created (every 10).  Is there anything else that needs to be adjusted or added to it?

**Comment by richardlara67** [comment]
Completed by Jordan.
